name: Main
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install tools
      env:
        GOPATH: /home/runner/work/go
      run: |
        mkdir -p ${GOPATH}
        sudo apt update
        sudo apt-get install -y build-essential devscripts debhelper gettext-base
        go get fyne.io/fyne/v2/cmd/fyne

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Package
      env:
        GOPATH: /home/runner/work/go
      run: |
        cd ./cmd/shutterlimitswitchsetup
        ${GOPATH}/bin/fyne package -os android/arm -appID hu.balazsgrill.shutterlimitswitchsetup -icon icon.png
    
    - uses: actions/upload-artifact@v1
      with:
        name: android package
        path: "cmd/shutterlimitswitchsetup/shutterlimitswitchsetup.apk"

    
